### ISSUE TITLE
Akonadi should default to SQLite instead of MySQL/MariaDB

### ISSUE THREAD

**Issue by livingsilver94** [snekpit/plasma#2]
Just a reminder for myself and a place for discussion.

Akonadi requires a relational DB for its functions. IMO using a server-grade DBMS for a desktop usage is just overkill, we can save runtime resources and space by not installing MariaDB. KDE documentation says SQLite is unsafe but I believe this is an outdated statement. I volunteer to test the SQLite backend and report whether it works fine these days.

**Comment by livingsilver94** [comment]
# How to

1. Have an `akonadi-backend-sqlite` package
2. Install such package
3. Provide a default configuration file for akonadi like this:
```
[%General]
Driver=QSQLITE3

[QSQLITE3]
Name=$HOME/.local/share/akonadi/akonadi.db
```

The `$HOME` variable expansion is to be tested, I'm not sure about it. Otherwise, just use some path inside `/var`.

**Comment by ReillyBrogan** [comment]
> KDE documentation says SQLite is unsafe but I believe this is an outdated statement

I'd much rather have an explicit statement from the Akonadi devs on this subject. It appears that [kde-pim](https://mail.kde.org/mailman/listinfo/kde-pim) is the correct mailing list, can you email a request for clarification to that?

**Comment by livingsilver94** [comment]
Yeah sure.

**Comment by livingsilver94** [comment]
Looks like SQLite3 is a viable solution! https://mail.kde.org/pipermail/kde-pim/2023-April/049426.html

**Comment by ermo** [comment]
Serpent is going to be GNOME-only for MVP, so closing as not planned.
